### ISSUE TITLE
bq website down

### ISSUE THREAD

**Issue by fabriba** [adriangl/adriangl#1]
Hi man,
sorry to disturb, I used to download roms for my **aquaris x2 pro** from bq website, but it's now down and I cannot find them anywhere.

The only entry google finds of the string **3.1.5_20201014-0835** (the latest rom version) is pointing to your git repo, but I still don't find the compiled versions... and yet I know they must be available somewhere as my phone managed to download and install that.

Can you please point me in the right direction?

Thank you!!

**Comment by adriangl** [comment]
Hi @fabriba!

I don't work in FW development in bq, so I don't know where you can download the compiled FWs for your phone now that the website is down.

Unfortunately the [Web Archive cached page](http://web.archive.org/web/20200923145730/https://www.bq.com/es/support/aquaris-x2-pro/support-sheet) only has up until September FWs, so that would most likely not work for you.

You may want to try and send an e-mail to opensource@bq.com to see if they can provide you the compiled version that you ask for 😁

**Comment by adriangl** [comment]
Hi again @fabriba!
Just a quick comment: you may want to check this Telegram group where you can find lots of FW binaries gathered by the user `Raw Main` of HTCMania forums: https://t.me/bqrepo

Hope you find it useful!
