### ISSUE TITLE
Using Pic2Cam

### ISSUE THREAD

**Issue by bugrayildiz1** [adriangl/adriangl#3]
Hey Adrian,

My name is Bugra and I am currently third year Technical Computer Science student at University of Twente. I am currently working on a project for changing the camera input with the pre recorded image or video. I downloaded Pic2Cam app and I have a question about it. 

Some apps use their own camera implementation and I wanted to ask if it is possible to use pic2cam app on those kind of applications. If so, how? Please let me know if you can help me about it. 

Regards,

Bugra Veysel Yildiz

**Comment by adriangl** [comment]
Hello Bugra!

First of all, sorry for the late reply. 

About the question you ask, no, Pict2Cam is unable to replace the device's camera stream: it just hooks into Android's Intent system to get app camera requests performed by launching an Intent with the `IMAGE_CAPTURE` action. That's why Pict2Cam only allows replacing these app requests.

It would be ideal to replace the camera stream with a static image of video of some sort -maybe creating a virtual camera input? I don't know if it's possible in Android, but it is on PCs, for example- and making apps pick that stream by default (you would probably need to override the default camera input and ID in some way so it picks the virtual one), but I'm not sure if that would be possible at all as I don't know that much about Android internals.

I'm sorry that I can't give you more information about this, but at least I hope that it can help you in some way with your project. Oh, and keep me updated if you find anything useful about the matter if you don't mind 😁.

Regards
